redding/assert

lib/assert/cli.rb
lib/assert/runner.rb
lib/assert/test.rb
lib/assert/view/base.rb
lib/assert/view/default_view.rb
test/unit/view_tests.rb

This updates the runner to catch `Interrupt` exceptions and to fire
a new view callback `on_interrupt` before re-raising the interrupt.
This allows view handlers to handle the interrupt scenario.
This also updates the default view to dump its test results on
interrupt just like it would on finish.  This allows you to
interrupt a long test suite run that is producing a bunch of errors
and see what those errors are before having to wait for the test
suite run to finish.
Closes #207.

dump test results on interrupt

---

lib/assert/context/subject_dsl.rb
lib/assert/macros/methods.rb
lib/assert/test.rb
test/support/factory.rb
test/unit/test_tests.rb

Using the context info's called from attribute, we can pull out
and track which file and line number a test is defined on.  This
will allow running tests by file/line-number and is prep for that
feature.
Note: this also updates the methods macro to properly pass called from
context to its test definition.  The single methods test will be
seen a defined on the line of the first methods macro in the test
file.  I noticed this was incorrect while debugging for the file
line number change.
Note also: this updates assert's own factory to extend assert factory.
This opens up all the factory methods for use in assert's own test
suite.  Note really sure why this wasn't done already - it was 
probably just missed.  I switched to using factory methods to build
the context info called from factory. …

track the file and line number for each test

---

lib/assert/file_line.rb
lib/assert/test.rb
test/support/factory.rb
test/unit/file_line_tests.rb
test/unit/test_tests.rb

This adds a helper class for dealing with test file/line-numbers.
It includes the basic readers but also defines how these are
represented in strings and also how to parse from a string.  It
also encapsulates comparison logic.
In addition, this defines an `AnyFileLine` utility class.  This
class is special in that it will be equal to any file line it is
compared with.
`Test` has been backported to track its file line.  This will be
used in the coming run-by-line-number feature.  File lines will
be taken as args from the cli and only run tests with matching file
lines will be run.  This will also be used on the coming verbose
output feature as we will display the test's file line in the
output.
Related to #120.

`FileLine` helper class for file/line-number handling

---

README.md
lib/assert/cli.rb
lib/assert/config.rb
lib/assert/view/default_view.rb
lib/assert/view/helpers/common.rb
test/unit/config_tests.rb
test/unit/view_tests.rb

This adds a verbose runtime output mode flag to the CLI and config.
This also adds a method for querying this flag to the common view
helpers.  Finally, this updates the default view to honor the
flag in its output.
This goal here is to be able to give more details about what is
running at runtime.
Closes #208.
@jcredding ready for review

verbose output mode

---

README.md
lib/assert/cli.rb
lib/assert/config.rb
lib/assert/utils.rb
test/unit/config_tests.rb

This updates the CLI and default changed proc to take a reference
value.  The goal here is to optionally pass a reference argument
when evaluating changed tests.
Practically, this can be used to test changed tests 1) after they
have been staged (`assert -cr HEAD`) or 2) after they have been
committed to a branch (`assert -cr master`).
This closes #214.

changed ref CLI opt

---

lib/assert/assert_runner.rb
lib/assert/cli.rb
lib/assert/config.rb
test/unit/config_tests.rb

Use this option to list out the test files the *would be* loaded
and run to stdout.  There are two goals here: 1) use this to help
debug and 2) use in a script to run each test file individually.
Note: this reorganizes the CLI options to list in a more relevent
order.  This also reorganizes the config option settings to group
them together and order them in the same order as the CLI defines
them.  Just cleanups and readability improvements here.
Closes #216.
Closes #215.

`-l` option for listing out test files that would be loaded and run

---

lib/assert/config_helpers.rb
lib/assert/runner.rb
lib/assert/suite.rb
lib/assert/view/base.rb
lib/assert/view/helpers/common.rb
test/unit/config_helpers_tests.rb
test/unit/suite_tests.rb
test/unit/view_tests.rb

Really these helpers can be used on anything that provides a `config`
method.  This is prep for making the runner more powerful and
implementing a multi-process runner.
The runner will need to have some of these helpers available so
I figured why not make all config-based helpers available since the
runner knows its config.
In addition, this adds tests for all of the config helpers.  These
were previously untested.  There are also a number of minor cleanups,
mainly to some old tests, that I noticed while making these changes.
@jcredding ready for review.  I'm going through and making some cleanups to Assert internals in prep for doing Parassert.  I'll have a number of PRs all related to this.  None of these should change the external API or behavior - just reorganizing and making it …

break out common config helpers to share between runner/view

---

lib/assert/default_view.rb
lib/assert/runner.rb
test/unit/runner_tests.rb

Before, the runner just fired events on the view and the view
could determine what to say on start.  However, the default view
would make assumptions about the runner and say that we are running
tests in random order when in fact this may not be true.
This moves the logic of describing the run into the runner as it
isn't a view's concern.  This is prep for intending the runner to
be extended - different runners may want to both use the default view
but may run their tests in different manners.
Note: the view continues to have no control on the order that output is
displayed - the runner controls when events are fired which controls
when the different output pieces are displayed.

have runner describe how tests are going to be run

---

lib/assert/config.rb
lib/assert/default_view.rb
lib/assert/view.rb
test/unit/view_tests.rb

This removes the ability to dynamically specify view configs/suites.
This ability isn't really serving any purpose and is an artifact
of legacy implementations.  This is prep for Parassert - making
the core objects more intentionally extendable.
I also chose to change it so that you pass the config as the first
arg to the view constructor.  This makes is consistent with the
suite and runner objects.  I'm trying to centralize all handling
around the config object and locking things down so that the config
truly drives all settings.  #221 and #222 started this effort by
centralizing the helpers around the config object.

simplify, standardize view constructor

---

lib/assert/assert_runner.rb
lib/assert/runner.rb
test/unit/runner_tests.rb

This is similar to 226 and is prep for doing Parassert.  The goal
here is to make the runner intentionally extendable yet as simple
to work with as possible.  This also continues the efforts of 221
and 222 to make the config the common central point for all settings.
The `run` methods dependency injection is an artifact of previous
implementations and currently serves no purpose.  It only adds
complexity.
See #221, #222 and #226 for reference.

simplify runner run method; remove suite/view injection

---

lib/assert/factory.rb
test/unit/factory_tests.rb

In hindsight this was to big of an assumption about the makeup of
a slug.  This switches to a simpler, more basic and more general
representation of a slug.  I chose to use a 5 char string by default
to help differentiate it from string factories.

update `slug` factory; don't have it include dashes

---

lib/assert/context.rb
lib/assert/context/test_dsl.rb
test/unit/context/test_dsl_tests.rb
test/unit/context_tests.rb

So you can create "skip tests" using the `{test|should}_eventually`
methods or by creating a test with no given block.  These tests
automatically create a single skip result and (in the eventually
methods case) don't run any test code.
However, the results these skip tests produced had a backtrace that
was internal to assert as the skip call was happening from internal
assert code.  When the results were rendered they would appear to
have no trace info b/c the internal assert backtrace lines were all
being filtered out.
This fixes the issue by passing in the test called from info in to
the skip call.  If called from info is passed in to the skip call,
it updates the skip exception backtrace to the called from.  This
allows proper trace info to show up for the skip test results.
Note: this …

bugfix: include the test backtrace on skip tests

---

lib/assert/assert_runner.rb
lib/assert/runner.rb
lib/assert/view.rb
test/unit/view_tests.rb

Remove the ceremony of going through a custom dispatch method.  Just
call the methods directly.  There was nothing wrong with the previous
implementation, I'm just trying to simplify things.  This also updates
the callbacks comment to make it more accurate.
This is prep for adding a similar callback setup for the suite and
the runner.

remove `fire` method on the base view

---

lib/assert/config.rb
lib/assert/context.rb
lib/assert/context/test_dsl.rb
lib/assert/context_info.rb
lib/assert/default_suite.rb
lib/assert/runner.rb
lib/assert/suite.rb
test/support/factory.rb
test/unit/config_tests.rb
test/unit/context_info_tests.rb
test/unit/default_suite_tests.rb
test/unit/runner_tests.rb
test/unit/suite_tests.rb

This reworks the suite object to make it more flexible to extend.
This follows the pattern of the view object where the base suite
provides the core logic/behavior and the default suite provides
the default assert behavior.  The goal here is to enable extending
the suite for use in AssertSqlite (and Parassert).
The suite is responsible for accumulating tests for the runner to
run and for providing the run data and test result data.  The default
suite stores run data and results in memory.
Note: this begins the work of formalizing the test/result data api.
In a coming effort, I'll rework the default view to fully use this
api and implement the full api in the default suite.
There are a few other smaller changes here:
* I broke out the context info class into its own top-level object.
This …

rework suite implementation/handling; add DefaultSuite

---

README.md
lib/assert/default_view.rb
lib/assert/view.rb
test/unit/runner_tests.rb
test/unit/view_tests.rb

This is a purely organizational change.  The goal here is to make
the view implementation more closely match the new suite implementation
and to remove some legacy ceremony/complexity with view handling.
The diff is rugged b/c there was a tab indention change - there are
no behavior changes here.

update view to no longer use a base class

---

lib/assert/assert_runner.rb
lib/assert/config_helpers.rb
lib/assert/context.rb
lib/assert/default_suite.rb
lib/assert/default_view.rb
lib/assert/result.rb
lib/assert/suite.rb
lib/assert/view_helpers.rb
test/unit/config_helpers_tests.rb
test/unit/context/suite_dsl_tests.rb
test/unit/default_suite_tests.rb
test/unit/result_tests.rb
test/unit/suite_tests.rb
test/unit/view_helpers_tests.rb

Before the view gathered its data partially from the suite and
partially processed it on its own.  This would break if the suite
implements custom ways of storing and making data available.
This reworks the views and view helpers to get all data from the
suite and updates the default suite to implement all suite behavior
by storing data in memory and processing it in memory.
This is prep for assert-sqlite where its suite will not store data
in memory but will instead store it in the db and query the db for
data processing.
There are a few other tweaks I've added here:
* added `output` to the result api and handling - it is needed by
the views and should have been added originally
* switched from array `count` to array `size` - supposedly it is
faster: …

update view to get all test/result data from the suite

---

lib/assert/assert_runner.rb
lib/assert/config.rb
lib/assert/default_runner.rb
lib/assert/runner.rb
test/unit/config_tests.rb
test/unit/default_runner_tests.rb
test/unit/runner_tests.rb

This updates the runner logic so that it can be intentionally
subclassed with extra behavior, much like the suite and view.  This
also adds a default runner implementation.  This is prep work for
doing Parassert - it will define a custom runner that will run
tests in parallel.
The base runner has all the structured run procedures and handling.
Custom runners must define a `run!` method which should yield tests
to run to the given block.  They can also define callbacks for extra
custom behavior.
This also updates the runner to call all of its own callbacks and
all of the suite's callbacks in addition to the view callbacks. This
fully implements the callback system between all of the objects.

add DefaultRunner

---

test/unit/config_helpers_tests.rb
test/unit/result_tests.rb
test/unit/view_helpers_tests.rb
test/unit/view_tests.rb

Looks like Matz renamed this in ruby commit 9295fd4b5, almost exactly 8 years ago.
Running assert on itself, with a current ruby (tested with 2.2.3p147), shows 16 errors
resulting from the lack of a 'choice' method on Array.

Ruby changed Array#choice to Array#sample

---

test/helper.rb

The test suite was updated to use `Array#sample` instead of
`Array#choice` in 239 so that the test suite would pass in modern
ruby versions.  However, I would prefer that the test suite continues
to pass in ruby 1.8.7 as well.
This backfills the `sample` method so that tests will pass in 1.8.7.
See #239 for reference.
@jcredding ready for review.  You good with this backfill implementation?

backfill Array#sample so tests pass in ruby 1.8.7

---

lib/assert/runner.rb

Not including it has been around since the beginning (see e4a019a).
I don't see a good reason to not include it though.  We include
the setup/teardown of each test.  Plus not including it makes the
reported test suite run times shorter than the actual perceived
run time.
I say let's include the in the total run time so it is more honest
and better matches perceived run times.
@jcredding ready for review.  You OK with this man?  Any concerns I'm missing in changing this?

include one-time suite setups/teardowns in total test run time

---

lib/assert/config_helpers.rb
lib/assert/default_view.rb
lib/assert/runner.rb
lib/assert/suite.rb
lib/assert/view.rb
test/unit/config_helpers_tests.rb
test/unit/runner_tests.rb
test/unit/suite_tests.rb
test/unit/view_tests.rb

This cleans up some usage of the config helpers in the runner, suite
and view.  The config helpers now formally define each object so
the things mixing in the config helpers don't have to.
Now the runner no longer manually has to define the objects it needs.
I also had each object override the config helpers that define
themselves.  Finally, this renames the run time and rates to include
`formatted_` in the name.  The previous name collided with with
the corresponding names on the suite.  It wasn't causing problems, it
was just bad form.
This is more prep for switching to have the tests accumulate result
data rather than store it as objects in memory.

formalize the runner, suite and view in the config helpers

---

lib/assert/default_view.rb
lib/assert/view.rb
lib/assert/view_helpers.rb
test/unit/view_helpers_tests.rb
test/unit/view_tests.rb

This method really only applies if you are using ansi stuff in your
view.  There is no need to have this in the base view.  This moves
the method to the Ansi view helper module and updates the default
view to mixin that module as it needs the helper.  This will help
reduce bloat when building non-ansi views.
This is a cleanup to prep for reworking/simplifying the views when
we switch to accumulating test result data.

move the `ansi_styled_msg` helper method out of the base view

---

lib/assert/default_runner.rb
lib/assert/runner.rb
test/unit/default_runner_tests.rb
test/unit/runner_tests.rb

This moves the logic/handling for randomizing the test run order
out of the default runner and into the base runner.  I'm essentially
saying this is not something that is intended to be overridden.
This is prep for adding logic to just run just single tests.  I want
to centralize the "baseline" features into the the base runner so
they are always available, no matter what runner is in use.  This
is also prep for adding a custom runner that runs tests in parallel.
It shouldn't have to re-implement this kind of basline behavior.

runner: move test randomization to the base runner

---

lib/assert/assert_runner.rb
lib/assert/cli.rb
lib/assert/config.rb
lib/assert/config_helpers.rb
lib/assert/file_line.rb
lib/assert/runner.rb
test/support/factory.rb
test/unit/config_helpers_tests.rb
test/unit/config_tests.rb
test/unit/file_line_tests.rb
test/unit/runner_tests.rb

This updates assert's base runner to allow running only a single
test.  The idea is to not only be able to isolate failing tests
and work on just them but also to print out assert CLI commands
in fail/error messages to allow you to easily re-run only a single
failing test for quick iterations.
To accomplish this I've added a new cli opt, `-t`, that takes the
file/line of the single test to run.  For example:
```
$ assert -t test/unit/config_tests.rb:61
```
This option configures the file line for the single test and puts
assert in "single test" mode.  Only the test file for this test
will be loaded and only that single test will be run.  If an invalid
file/line is specified, no tests are run.
Some addtional notes:
* `-t` was used b/c you are calling out a test - t for test
* the file line …

runner: add `-t` option to run only a single test

---

lib/assert/default_view.rb
lib/assert/result.rb
lib/assert/view_helpers.rb
test/unit/result_tests.rb
test/unit/view_helpers_tests.rb

Now that we can run individual tests using the new `-t` option,
a common need is to re-run just a single test that is failing and
we want to focus on.  This updates the result details that are dumped
by the default view to build and include an assert cmd for re-running
just that result's test.
To make this happen, I first needed to track the `test_id` on each
result.  The test id is just the file/line string for the result's
test.
I chose to print the command with no empty lines between it and the
rest of the result details b/c we currently don't put any empty lines
in the result details.  I chose to not ansi color it to help make it
stand out from the rest of the details.  This is similar to how we
output captured output for each result.

output the cmd to re-run a result's test in result details

---

README.md

This describes not only running a single test but also how Assert
prints single test run cmds on failed results.  This is to keep
the README relevent and helpful as we add new options to Assert.

readme: add description of the new `-t` option

---

README.md
lib/assert/assert_runner.rb

Previously, ENV settings would be applied last and could therefore
override CLI settings.  It seems strange in hindsight to ever override
something that has been specified at the CLI.  It leads to confusing
and unpredictable behavior as you may not realize and ENV var is
even set.
This switches to always applying CLI settings last so that they
are never overridden.  I also chose to reorder some of the implementation
to match the order b/c that is what was done previously.  I also
updated the README to keep it relevent and matching the implementation.

switch to applying CLI options last

---

lib/assert/assertions.rb
test/unit/assertions/assert_raises_tests.rb

The goal here is to be able to do further assertions against any
raised exception while still explicitly asserting a specific kind
of exception was raised.
@jcredding ready for review

have `assert_raises` return any raised exception instance

---

lib/assert/assert_runner.rb
lib/assert/cli.rb

This addresses issue 256.  On test suites that are large (many test
files to require or complicated env setup in the test helper), debug
mode is only somewhat helpful.  On the longer init steps (ie requiring
the test helper and requiring the test files) assert would just stare
blankly at you while stuff was happening but you didn't know what
it was doing.  Only once the step was complete did you know what it
was doing.  This is not great UX.
This updates the bench logic to pring the debug msg immediately to
show that this step has begun and we are waiting on it.  Then
when the step is done the timing info is displayed as before.  This
lets the developer see that something is going on and start mentally
estimating how long it has taken so far.
This also justifies the output so the timing …

debug mode: bench showing debug msg immediately; show timing on finish

---

README.md
lib/assert/stub.rb
test/unit/assert_tests.rb
test/unit/stub_tests.rb

One shortcoming of using stubs was that it was difficult to call
the original method you were stubbing within your stub.
For example, say you wanted to stub a method just to spy on what it was
being called with.  In this case, you don't want to change what the
method returns, you just want to capture the args it was called with.
You would setup a stub like:
```ruby
meth_called_with = []
Assert.stub(myobj, :meth) do |*args|
meth_called_with = args
end
```
The problem is what do you return from this stub?  Some fake value?
It is even worse when stubbing the `:new` method:
```ruby
obj_init_with = []
Assert.stub(myobj, :new) do |*args|
obj_init_with = args
end
```
To address this problem, there is a new singleton method: `Asset.stub_send`
to allow calling the original stubbed method from …

stubs: call to original method using `Assert.stub_send`

---

lib/assert/stub.rb
test/unit/assert_tests.rb
test/unit/stub_tests.rb

Previously, the backtraces of the stub errors would be nested in
the internals of the stubbing implementation.  This is really
confusing b/c you really want the backtrace to point to where the
problem originated so that the user is shown what they need to change.
This updates the stubbing internals to capture the original caller
for any calls that may raise stubbing errors.  This original caller
is then used as the backtrace for all stub errors.
Note: this also makes the newly added `stub_send` raise a `NotStubbedError`
when trying to call the original method on something that hasn't
been stubbed.  This is consistent with the other stub methods and
should have been done in PR 258 where this method was originally
added but was missed.
See #258 for reference.
@jcredding ready for review.  I …

stubs: have stub errors use the backtrace of the original caller

---

lib/assert/runner.rb
test/unit/runner_tests.rb

When adding the single test mode back in PR 250, I ended up only
applying the runner seed if you were running in non-single test mode
(ie not using the `-t` option flag).  On the surface this kinda sense
b/c the seed drives the test order randomization. If you are only
running one test you don't need test randomization.
However, the intent is that this seed also drives the pseudo random
generator (`srand`). This impacts the values that are generated by
Assert's factories. We need to always apply the seed info so that you
can re-run a single test and get the same factory values out.  This
update ensures that whether running in single or multi test mode, the
seed value is always applied.
See #250 for reference.
Closes #262.
@jcredding ready for review
@nweathersbee FYI.

apply runner seed whether running single or multiple tests

---

lib/assert/config_helpers.rb
lib/assert/default_view.rb
lib/assert/runner.rb
lib/assert/suite.rb
lib/assert/test.rb
lib/assert/view_helpers.rb

I made a bunch of notes of things to change when switching to
accumulating test results.  Currently we store every test object
and every result generated by every test.  This is inefficient
for calculating summary info at the end of the test run and is
unnecessary as we don't need to store all of this data.  Plus
the overhead on large test suites is significant.
In this overall effort, I plan on switching to not storing every
test.  Instead, tests will be shifted off as they are run and
only result data needed for presentation will be accumulated.
This should save memory not storing as many objects and should
make rendering summary presentation data more efficient.
@jcredding copy of #264 made against a feature branch - FYI.

accumulate: prep notes for accumulating test results

---

lib/assert/config_helpers.rb
lib/assert/context.rb
lib/assert/context/test_dsl.rb
lib/assert/default_suite.rb
lib/assert/default_view.rb
lib/assert/runner.rb
lib/assert/suite.rb
lib/assert/view_helpers.rb
test/unit/config_helpers_tests.rb
test/unit/default_suite_tests.rb
test/unit/runner_tests.rb
test/unit/suite_tests.rb
test/unit/view_helpers_tests.rb

This is part of switching to accumulating test run and result data.
This is specifically prep for removing the `tests` reader on the
suite.  Since we will be accumulating data, there will be no need
to keep a list of all the tests in memory.
I chose to move the storage of tests as an array into the default
suite as opposed to the base suite.  I don't want to force storing
tests in memory on all suites.  Some suites may choose to store
their tests to run some other way.
I chose to add an `on_test` callback for adding tests to the suite.
This follows the callback pattern used for other custom behavior
(ie `on_result`) and removes needing to access the raw list of
tests outside of the suite.
I chose to add a method to clear the tests to run.  This is prep
for clearing out the tests from …

accumulate: rework suite to abstract the tests to run

---

lib/assert/config_helpers.rb
lib/assert/default_suite.rb
lib/assert/default_view.rb
lib/assert/runner.rb
lib/assert/suite.rb
lib/assert/view_helpers.rb
test/unit/config_helpers_tests.rb
test/unit/default_suite_tests.rb
test/unit/runner_tests.rb
test/unit/suite_tests.rb
test/unit/view_helpers_tests.rb

This is part of switching to accumulating all test run data and not
storing unnecessary data like every test obj that was run and every
result obj that those tests produced.
This replaces the super-generic `count` method (that would count any
tests data) with data-specific count methods.  These count methods
pull from the counts accumulated on the suite rather than actually
counting up objects in memory.  Counts are accumulated by implementing
callbacks and incrementing counters appropriately.  I chose to use
specific increment private methods for incrementing the typed
result counts to avoid having to do some conditional or some
dynamic ivar get/set.
I also added some more notes for the coming steps like moving
presentation data accumulation/handling into the view, etc.
@jcredding ready …

accumulate: store/accumulate test/result counts on the suite

---

lib/assert/default_suite.rb
lib/assert/runner.rb
lib/assert/suite.rb
test/unit/default_suite_tests.rb
test/unit/suite_tests.rb

This builds off the original abstract effort from PR 266.  I realized
I had moved to not use the `tests` reader, but in doing so had just
replaced this reader with a new `tests_to_run` reader.  This kinda
missed the original point.
This switches to letting the suite define how to lookup a single
test by file line and sorting the tests given a `sort_by` proc. I
chose to pass in the sort by proc so the runner continues to force
that the tests are sorted randomly and to continue jux'ing the srand
and rand logic in the runner.
In particular, the sort method taking a `sort_by` proc implies that
a `sort_by` call will be made which implies that at some point
the tests will be in an enumerable in memory.  This makes me wonder
if my choice to move storing test in memory only in the default
suite …

accumulate: abstract suite `tests_to_run`

---

lib/assert/default_suite.rb
lib/assert/default_view.rb
lib/assert/result.rb
lib/assert/suite.rb
lib/assert/view_helpers.rb
test/unit/default_suite_tests.rb
test/unit/result_tests.rb
test/unit/suite_tests.rb
test/unit/view_helpers_tests.rb

This implementation no longer relies on the result objects stored
on each test object that was run.  This is part of switching to
no longer storing test objs that were run and the result objs those
tests produced.
This new implmentation accumulates the results that need to be
dumped as results come in.  This has a few advantages over the
previous implementation.  For starters, not needing to store results
means we use less memory in the test suite (which has a big impact
on large test suites).  Also, this decouples the result object
from the default view b/c we store result data custom to the view.
Only the attrs that need displaying will be stored.  Finally, this
only has to sort a subset of all results generated (the ones that
need to be dumped).  This is more performant on large test …

accumulate: rework the default view to accumulate results to dump

---

lib/assert/config_helpers.rb
lib/assert/default_suite.rb
lib/assert/default_view.rb
lib/assert/runner.rb
lib/assert/suite.rb
lib/assert/view_helpers.rb
test/unit/config_helpers_tests.rb
test/unit/default_suite_tests.rb
test/unit/suite_tests.rb
test/unit/view_helpers_tests.rb

This implementation no longer relies on the test objects stored
on the suite. This is part of switching to no longer storing test
objs that were run and the result objs those tests produced.
This new implementation optionally accumulates test data needed for
presentation.  This test data is only needed if running in verbose
mode or profiling.  Test data is stored by its file line in a hash
on the view.  As results come in, the test data's result count is
incremented.  When the test is finished, the run time and result
rate are captured.  This, plus the static attrs captured when the
test begins, is all the data needed for presentation in both the
verbose and profile scenarios.
Due to these changes all of the suite's test handling methods can
be removed. All test handling is now expected …

accumulate: rework the default view to accumulate test data

---

lib/assert/default_view.rb
lib/assert/result.rb
test/unit/result_tests.rb

Previously, the data just stored the file_line string which did not
sort the file line number portion as intended b/c string integers
don't sort like integers.  This switches the storing the file name
and line number of the result independently and using those to
properly sort the results by reverse definition order.
This edge case was missed in PR 269 but was missed.  This is part
of the effort to accumulate test run data instead of storing test
objects.
See #269 for reference.

accumulate: properly sort result data by the file name and line num

---

lib/assert/default_suite.rb
lib/assert/suite.rb
test/unit/context/test_dsl_tests.rb
test/unit/default_suite_tests.rb
test/unit/runner_tests.rb
test/unit/suite_tests.rb

It was premature to assume this behavior was specific to just the
default suite.  Any suite, regardless of how they accumulate test
or result counts, will need to keep the tests in memory as they
need the test code blocks to run.  I discussed the likely need to
do this back in PR 268.
This also removes the tests accessor on the suite and updates the
descriptions of both the suite and default suite.  The tests that
were relying on the tests accessor were updated accordingly to use
the proper test handling methods on the suite.
This is all part of the effort to accumulate test run data instead
of storing off the actualy test objs and the result objs they
produce.
See #268 for reference.

accumulate: move in-memory test handling back to base suite

---

lib/assert/assertions.rb
lib/assert/context.rb
test/unit/context_tests.rb

This is prep for no longer storing results on tests.  We can't rely
on a test knowing its results going forward.  I already broke this
method back in PR 269 b/c results are getting accumulated before
this method could set the proper backtrace on them.  This fixes
the regression and preps for a test not knowing its results anymore.
Note: this does some cleanups to the `__whatever__` variables/methods
on the context.  These weirdly named vars are needed by the context
but we don't want to pollute the variable/method space b/c users
will be defining their own variables/methods.  I updated the handling
of these just as cleanups and I added `assert` to each one's name
to add extra protection against name collisions with user defined
things.
See #269 for reference.

accumulate: update `with_backtrace` to not rely on test `results`

---

lib/assert/default_view.rb
lib/assert/file_line.rb
lib/assert/result.rb
test/unit/file_line_tests.rb
test/unit/result_tests.rb

This is part of reworking assert to accumulate test run data and
came out of trying to remove the `results` accessor from the test
object (a future effort).  In working on this effort, I broke a
bunch of tests.  I noticed that the test results weren't ordered
as I expected and I started to investigate.
The first thing I noticed was that for the error result backtraces,
the line used for the result file line included extra characters
after the line number (`".../test_tests.rb:123 in some_method"` for
example).  The file line wasn't parsing the backtrace lines
correctly.  So I updated the file line to properly parse backtrace
lines in this form.
Once that was corrected, I noticed that errors that occurred in
Assert's lib source code were being shown first, regardless of the
definition order …

accumulate: more fixes to result handling and view sorting

---

test/helper.rb
test/system/test_tests.rb
test/unit/assertions/assert_block_tests.rb
test/unit/assertions/assert_empty_tests.rb
test/unit/assertions/assert_equal_tests.rb
test/unit/assertions/assert_file_exists_tests.rb
test/unit/assertions/assert_includes_tests.rb
test/unit/assertions/assert_instance_of_tests.rb
test/unit/assertions/assert_kind_of_tests.rb
test/unit/assertions/assert_match_tests.rb
test/unit/assertions/assert_nil_tests.rb
test/unit/assertions/assert_raises_tests.rb
test/unit/assertions/assert_respond_to_tests.rb
test/unit/assertions/assert_same_tests.rb
test/unit/assertions/assert_true_false_tests.rb
test/unit/assertions_tests.rb

This reworks a bunch of the assertion tests and system tests to
not expect a test to know its results.  This is prep for removing
the `results` accessor from tests, which in turn is part of switching
to accumulating test run data.
I chose to break out a test helpers module so I could include it
on all the test contexts.  Since the tests all needed to accumulate
results and tested the results in a similar manner, this commonization
works.
I chose to break this out into a separate PR to remove some noise
from the coming effort where I remove the `results` accessor on
the Test class.

accumulate: prep tests for removing `results` from test objects

---

lib/assert/context.rb
lib/assert/test.rb
test/unit/test_tests.rb

This reworks the `capture_result` behavior in both the Test and
Context objects.  This is part of the cleaning up now that we are
accumulating test run data instead of storing it on the test objs.
This Context capture removes an unnecessary `yield` call and instead
builds the result itself from given/static inputs.  There is no need
to go through the ceremony of yielding to the given block to get
a result.  Because the test and caller params are static/common
to all results, we only need to be given the result class and msg.
This simplifies everywhere we call `capture_result` and should
give a slight performance improvement.  Plus there is no reason
to call to the test's `capture_result` as the test doesn't do any
extra logic on capture (it just calls the callback which we can
do …

accumulate: simplify `capture_result` in both test and context

---

lib/assert/runner.rb
lib/assert/suite.rb
test/unit/runner_tests.rb

This is a slight optimization related to now accumulating test run
data.  We no longer need to keep references to the tests-to-run
since we are accumulating their meta and result data.  This switches
to clearing out the suite tests-to-run just before the running
starts iterating them.  It also updates the runner to remove its
reference to the test as each test is done running.
Note: I had to update a couple of runner tests where they were
incorrectly relying on tests being available post-run.  This
should have been done back when I added these tests but was missed
b/c we kept the tests around and I just didn't notice at the time.

accumulate: clear out tests from the suite as they are run.

---

lib/assert.rb
lib/assert/context.rb
lib/assert/context/test_dsl.rb
lib/assert/context_info.rb
lib/assert/macros/methods.rb
lib/assert/result.rb
lib/assert/stub.rb
test/unit/context_tests.rb

So I've previously noticed that `caller` is a bit expensive in
processing time and is adding overhead to our test suites.  I set
out to look into alternatives and squeeze some performance out of
running tests in Assert.
In Ruby 2.0+ a new Kernel method, `caller_locations`, was introduced
that is significantly more performant than `caller`.  It also
returns an array of location objects instead of an array of Strings.
See:
* http://blog.marc-andre.ca/2013/02/23/ruby-2-by-example/#caller_locations
* https://stackoverflow.com/questions/5100299/how-to-get-the-name-of-the-calling-method (scroll down)
So, this sets out to switch to using `caller_locations` instead of
`caller` if in Ruby 2.0+.
First off, I wanted to keep Assert compatible with pre Ruby 2.0
(selfishly b/c we still have some legacy …

prefer using `caller_locations` over `caller`

---

README.md
lib/assert/default_view.rb
lib/assert/runner.rb
lib/assert/suite.rb
lib/assert/view.rb
test/unit/runner_tests.rb
test/unit/suite_tests.rb
test/unit/view_tests.rb

This feature is designed to give you hints about what is going on
in a long-running test suite without having to interrupt it. This
addresses issue 220.
The runner now traps the INFO signal and calls `on_info` callbacks
on itself, its suite, and its view.  The default view implements
this callback and dumps any accumulated results it has (so far) and
also outputs info about the currently running test.  It looks
something like this (for example, on my Mac dev machine):
```
Running tests in random order, seeded with "60909"
.....F..FF.........load: 1.71  cmd: ruby 17628 running 1.60u 0.36s
FAIL: Yet Another Thing should also even do something
Expected equals actual, diff:
--- expected
+++ actual
/[...]/tests.rb:178:in `block in <class:Tests>'
assert -t ./[...]/tests.rb:167
FAIL: Another …
```

trap INFO signal; use to display current test run info in default view

---

lib/assert/runner.rb

This signal is available on OSX but not on some Linux flavors (ie
BSD).  This switches to only trapping if the signal is available.
I noticed this while trying to run tests in CI envs (ie CircleCI).

only trap SIGINFO if available

---

.circleci/config.yml

This is the config GGem generates for our gems.  This sets up
running tests against Ruby 2.3, 2.4, and 2.5.  I'm going to try
and set this up with all of our gems as I touch them.  GGem will
automatically generate it for new gems going forward.

add CircleCI configuration from GGem

---

README.md
assert.gemspec
lib/assert/stub.rb
test/unit/assert_tests.rb

See https://github.com/redding/much-stub/pull/6 for reference.
This updates to the latest version of MuchStub and adds a proxy for
its new `.tap` API. This also updates the README to remove
abbreviations like MuchStub has and adds brief references to the
new tap API.
This makes the tap API available as you'd expect in Assert.

add `Assert.stub_tap`

---

assert.gemspec
lib/assert/stub.rb
test/unit/assert_tests.rb

This adds the new API methods: `stub_tap_on_call` and `stub_spy`
See https://github.com/redding/much-stub/pull/7 for details.
This also ups the required ruby version since MuchStub imposes
this restriction now anyway.

update to the latest MuchStub

---

assert.gemspec
lib/assert/stub.rb
test/unit/actual_value_tests.rb
test/unit/assert_tests.rb

This bring in the latest version which, in addition to keeping up
with the latest stuff, adds a `MuchStub.stub_on_call` that now
can be proxied/used.
This version also switches MuchStub::CallSpy to be a BasicObject
but that has no effect on Assert.

upgrade to the latest MuchStub

---

lib/assert/actual_value.rb
lib/assert/assertions.rb
lib/assert/context.rb
lib/assert/result.rb
lib/assert/suite.rb
lib/assert/test.rb
test/system/stub_tests.rb
test/unit/actual_value_tests.rb
test/unit/assert_tests.rb
test/unit/assertions/assert_changes_tests.rb
test/unit/assertions/assert_equal_tests.rb
test/unit/assertions/assert_raises_tests.rb
test/unit/assertions_tests.rb
test/unit/config_helpers_tests.rb
test/unit/context/test_dsl_tests.rb
test/unit/macro_tests.rb
test/unit/result_tests.rb
test/unit/suite_tests.rb
test/unit/test_tests.rb

This addresses Issue #244.
This was originally added, many years ago, to maintain backwards
compatibility with Test::Unit tests. This is no longer desired so
we are removing the legacy code.
This addresses Issue #302. These are just shorter aliases for
`.is{not_}_the_same_as` that are less to type.
This closes Issue #301.
This is an assertion helper to test before/after states of
a bit of code.
This addresses Issue #300.
This is a more convenient/standard way to get actual values that
should be procs. You can still manually pass a proc in as a
proc actual value OR you can use the block slot to pass in a proc
actual value implicitly.
This also added `Assert::ActualValue.not_given` to use to know
whether a non-block-slot actual value was given or not. I can't do
`nil` or "truthy" checks as …

remove Test::Unit; add new assertion helpers; allow passing block actual values via block slot

---

assert.gemspec
lib/assert/actual_value.rb

The pattern was extracted into a special-purpose gem so it can be
used in other apps/gems. This switches to using the extraction.
See https://github.com/redding/much-not-given/pull/1 for reference.

bring in much-not-given; use to implement Assert::ActualValue.not_given

---

lib/assert/stub.rb

This is consistent with the rest of the MuchStub proxying and
aliasing. The goal is to obfuscate the fact that Assert is
composing MuchStub to implement its stubbing API.

alias MuchStub::{Call|CallSpy}

---

lib/assert/config.rb
test/unit/config_tests.rb

This is a fairly common feature in other testing frameworks. Plus
it is good for Assert to support _some way_ of controlling the
seed value via an env var to compose Assert in other system
workflows and pipelines.

support SEED env var for setting runner seed values
